# Generated by Django 5.0 on 2025-12-28 00:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("name_tr", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Tür",
                "verbose_name_plural": "Türler",
                "db_table": "genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(db_index=True, unique=True)),
                ("imdb_id", models.CharField(blank=True, max_length=20, null=True)),
                ("title", models.CharField(max_length=255)),
                ("original_title", models.CharField(max_length=255)),
                ("overview", models.TextField(blank=True, null=True)),
                ("tagline", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "poster_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "backdrop_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                (
                    "runtime",
                    models.IntegerField(
                        blank=True, help_text="Dakika cinsinden", null=True
                    ),
                ),
                (
                    "vote_average",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(10.0),
                        ],
                    ),
                ),
                ("vote_count", models.IntegerField(default=0)),
                ("popularity", models.FloatField(default=0.0)),
                ("original_language", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("rumored", "Söylenti"),
                            ("planned", "Planlanıyor"),
                            ("in_production", "Çekiliyor"),
                            ("post_production", "Post Prodüksiyon"),
                            ("released", "Vizyonda"),
                            ("canceled", "İptal"),
                        ],
                        default="released",
                        max_length=20,
                    ),
                ),
                ("adult", models.BooleanField(default=False)),
                ("budget", models.BigIntegerField(default=0)),
                ("revenue", models.BigIntegerField(default=0)),
                ("homepage", models.URLField(blank=True, max_length=500, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "genres",
                    models.ManyToManyField(
                        blank=True, related_name="movies", to="movies.genre"
                    ),
                ),
            ],
            options={
                "verbose_name": "Film",
                "verbose_name_plural": "Filmler",
                "db_table": "movies",
                "ordering": ["-popularity", "release_date"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tmdb_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "profile_path",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("biography", models.TextField(blank=True, null=True)),
                ("birthday", models.DateField(blank=True, null=True)),
                ("deathday", models.DateField(blank=True, null=True)),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "known_for_department",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[
                            (0, "Belirtilmemiş"),
                            (1, "Kadın"),
                            (2, "Erkek"),
                            (3, "Diğer"),
                        ],
                        default=0,
                    ),
                ),
                ("popularity", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kişiler",
                "db_table": "persons",
                "ordering": ["-popularity"],
                "indexes": [
                    models.Index(fields=["tmdb_id"], name="persons_tmdb_id_5da132_idx"),
                    models.Index(fields=["name"], name="persons_name_9c6d3a_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="MovieCrew",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job", models.CharField(max_length=100)),
                ("department", models.CharField(max_length=100)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crew",
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_crew",
                        to="movies.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Film Ekibi",
                "verbose_name_plural": "Film Ekipleri",
                "db_table": "movie_crew",
            },
        ),
        migrations.CreateModel(
            name="MovieCast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "character_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("cast_order", models.IntegerField(default=0)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast",
                        to="movies.movie",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_cast",
                        to="movies.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Film Oyuncusu",
                "verbose_name_plural": "Film Oyuncuları",
                "db_table": "movie_cast",
                "ordering": ["cast_order"],
            },
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["tmdb_id"], name="movies_tmdb_id_472987_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["title"], name="movies_title_179e04_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["release_date"], name="movies_release_e1d0b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(
                fields=["-vote_average"], name="movies_vote_av_59cd2e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moviecrew",
            unique_together={("movie", "person", "job")},
        ),
        migrations.AlterUniqueTogether(
            name="moviecast",
            unique_together={("movie", "person", "character_name")},
        ),
    ]
