# Generated by Django 5.0 on 2025-12-28 01:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["-popularity"],
                "verbose_name": "Kişi",
                "verbose_name_plural": "Kişiler",
            },
        ),
    ]
