# Generated by Django 6.0 on 2025-12-29 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("movies", "0004_watchlist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTasteProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre_weights", models.JSONField(blank=True, default=dict)),
                ("favorite_actors", models.JSONField(blank=True, default=list)),
                ("favorite_directors", models.JSONField(blank=True, default=list)),
                ("preferred_decades", models.JSONField(blank=True, default=dict)),
                (
                    "rating_style",
                    models.CharField(
                        choices=[
                            ("generous", "Cömert"),
                            ("balanced", "Dengeli"),
                            ("harsh", "Eleştirel"),
                        ],
                        default="balanced",
                        max_length=20,
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(decimal_places=1, default=0, max_digits=3),
                ),
                ("total_rated_movies", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="taste_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı Zevk Profili",
                "verbose_name_plural": "Kullanıcı Zevk Profilleri",
            },
        ),
        migrations.CreateModel(
            name="MovieLensMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("movielens_id", models.IntegerField(db_index=True, unique=True)),
                ("tmdb_id", models.IntegerField(db_index=True)),
                ("imdb_id", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "movie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movielens_mapping",
                        to="movies.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "MovieLens Eşleştirme",
                "verbose_name_plural": "MovieLens Eşleştirmeleri",
                "indexes": [
                    models.Index(
                        fields=["movielens_id"], name="recommendat_moviele_23134b_idx"
                    ),
                    models.Index(
                        fields=["tmdb_id"], name="recommendat_tmdb_id_9e6c15_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RecommendationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recommendation_type",
                    models.CharField(
                        choices=[
                            ("content", "Content-Based"),
                            ("collaborative", "Collaborative"),
                            ("hybrid", "Hibrit"),
                            ("quick_match", "Hızlı Eşleşme"),
                            ("similar", "Benzer Filmler"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content_score", models.FloatField(blank=True, null=True)),
                ("collab_score", models.FloatField(blank=True, null=True)),
                ("final_score", models.FloatField()),
                ("was_clicked", models.BooleanField(default=False)),
                ("was_rated", models.BooleanField(default=False)),
                ("rating_given", models.IntegerField(blank=True, null=True)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to="movies.movie",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Öneri Logu",
                "verbose_name_plural": "Öneri Logları",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="recommendat_user_id_c1d076_idx",
                    ),
                    models.Index(
                        fields=["recommendation_type"],
                        name="recommendat_recomme_875cad_idx",
                    ),
                ],
            },
        ),
    ]
