# Generated by Django 6.0 on 2025-12-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_compatibilityscore_friendship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="E-posta"
            ),
        ),
    ]
