# Generated by Django 6.0 on 2025-12-29 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_watchlist"),
        ("users", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="favorite_genres",
            field=models.ManyToManyField(
                blank=True,
                related_name="fans",
                to="movies.genre",
                verbose_name="Favori Türler",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="onboarding_completed",
            field=models.BooleanField(
                default=False, verbose_name="Onboarding Tamamlandı"
            ),
        ),
    ]
