# Generated by Django 6.0 on 2025-12-29 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_friend_requests",
                    models.BooleanField(
                        default=True, verbose_name="Arkadaşlık İstekleri (E-posta)"
                    ),
                ),
                (
                    "email_recommendations",
                    models.BooleanField(
                        default=True, verbose_name="Film Önerileri (E-posta)"
                    ),
                ),
                (
                    "email_weekly_digest",
                    models.BooleanField(
                        default=True, verbose_name="Haftalık Özet (E-posta)"
                    ),
                ),
                (
                    "email_upcoming_movies",
                    models.BooleanField(
                        default=True, verbose_name="Yeni Film Bildirimleri (E-posta)"
                    ),
                ),
                (
                    "push_friend_requests",
                    models.BooleanField(
                        default=True, verbose_name="Arkadaşlık İstekleri (Push)"
                    ),
                ),
                (
                    "push_friend_ratings",
                    models.BooleanField(
                        default=True, verbose_name="Arkadaş Puanlamaları (Push)"
                    ),
                ),
                (
                    "push_recommendations",
                    models.BooleanField(
                        default=True, verbose_name="Film Önerileri (Push)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim Tercihi",
                "verbose_name_plural": "Bildirim Tercihleri",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("friend_request", "Arkadaşlık İsteği"),
                            ("friend_accepted", "Arkadaşlık Kabul Edildi"),
                            ("new_rating", "Yeni Puanlama"),
                            ("recommendation", "Film Önerisi"),
                            ("watchlist_reminder", "İzleme Listesi Hatırlatma"),
                            ("upcoming_movie", "Yakında Vizyona Girecek Film"),
                            ("weekly_digest", "Haftalık Özet"),
                            ("system", "Sistem Bildirimi"),
                        ],
                        default="system",
                        max_length=30,
                        verbose_name="Bildirim Tipi",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Başlık")),
                ("message", models.TextField(verbose_name="Mesaj")),
                (
                    "related_movie_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="İlişkili Film ID"
                    ),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Aksiyon URL",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Okundu mu?"),
                ),
                (
                    "is_email_sent",
                    models.BooleanField(
                        default=False, verbose_name="E-posta Gönderildi mi?"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Tarihi"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Okunma Tarihi"
                    ),
                ),
                (
                    "related_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İlişkili Kullanıcı",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Kullanıcı",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bildirim",
                "verbose_name_plural": "Bildirimler",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "is_read"],
                        name="notificatio_user_id_427e4b_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="notificatio_user_id_05b4bc_idx",
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="notificatio_notific_f2898f_idx",
                    ),
                ],
            },
        ),
    ]
